### ISSUE TITLE
Create 'Intro to Command Line' folder and slide content

### ISSUE THREAD

**Issue by tinuola** [girldevelopit/gdi-curriculum#33]
1. Read the [`_template` directory README](https://github.com/girldevelopit/gdi-curriculum/tree/main/_template).

2. Use [instructions in the `_template` directory](https://github.com/girldevelopit/gdi-curriculum/tree/main/_template#how-to-use-this-template) to create a new course folder:
- Folder name: `intro-command-line`
- Topic directory: [`tech-101`](https://github.com/girldevelopit/gdi-curriculum/tree/main/tech-101)

3. Copy slide content from [`GDI San Francisco Command Line repo`](https://github.com/gdisf/teaching-materials/tree/master/cli). 
- To copy code content, see `demo-gdi-slides.html` for the `<section>` snippet to use in the new slides.
- Review and update the course content for structure/accuracy/relevance.
- Ensure that slide content is well-formatted. 
- Copy images (if any is used) to the new course folder.

4. Copy **course description** and **tech requirements** from the SF repo to Marketing.md.

5. Copy **Topics covered** to `README.md` for the course folder.

**Comment by kmreiss** [comment]
Changes submitted for review
